name: iOS CI (unsigned archive)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Archive unsigned .app and upload artifact
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 公共 Runner 没有 beta Xcode，这里用稳定版。若你需要别的版本，改 xcode-version。
      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.4"

      # 可选：缓存 SPM 依赖（如果项目用到）
      - name: Cache SPM
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            ~/.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: ${{ runner.os }}-spm-

      # 无签名归档（iphoneos），不会导出 IPA，但会得到可用的 .app（需越狱/签名后装）
      - name: Clean & Archive (unsigned)
        run: |
          set -euxo pipefail
          xcodebuild \
            -project "IdeaCapture.xcodeproj" \
            -scheme "IdeaCapture" \
            -configuration Release \
            -destination "generic/platform=iOS" \
            CODE_SIGNING_ALLOWED=NO \
            clean archive \
            -archivePath build/IdeaCapture

      # 将归档里的 .app 打包为 zip，便于在 GitHub 下载
      - name: Zip .app
        run: |
          set -euxo pipefail
          APP_PATH="build/IdeaCapture.xcarchive/Products/Applications/IdeaCapture.app"
          ditto -c -k --sequesterRsrc --keepParent "$APP_PATH" "IdeaCapture-unsigned.zip"

      # 上传构建产物（.xcarchive + .app.zip）
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: IdeaCapture-build-${{ github.run_number }}
          path: |
            build/IdeaCapture.xcarchive
            IdeaCapture-unsigned.zip
          if-no-files-found: error
